=== MohammadAbraransar/PAWS-AND-HEARTS/legacy/pets.dtd
<!ELEMENT pets (pet+)>
<!ELEMENT pet (name,type,age,breed,status)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT breed (#PCDATA)>
<!ELEMENT status (#PCDATA)>

=== MohammadAbraransar/PAWS-AND-HEARTS/legacy/pets.xml
<?xml version="1.0"?>

<!DOCTYPE pets SYSTEM "pets.dtd">
<?xml-stylesheet type="text/xsl" href="pets.xsl"?>

<pets>

    <pet>
        <name>Bruno</name>
        <type>Dog</type>
        <age>2 Years</age>
        <breed>Labrador</breed>
        <status>Available</status>
    </pet>

    <pet>
        <name>Luna</name>
        <type>Cat</type>
        <age>1 Year</age>
        <breed>Persian</breed>
        <status>Available</status>
    </pet>

    <pet>
        <name>Rocky</name>
        <type>Dog</type>
        <age>3 Years</age>
        <breed>Beagle</breed>
        <status>Available</status>
    </pet>

</pets>
